### ISSUE TITLE
Extra files

### ISSUE THREAD

**Issue by noraj** [GeopJr/vitepressify#5]
As `crystal docs` doesn't accept any external file (outside README.md by default), it would be nice that [vitepressify](https://github.com/GeopJr/vitepressify) accepts some extra files (a bit like [yard does](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md#documenting-extra-files)).

**Comment by GeopJr** [comment]
All vitepressify does is setup a vitepress project, you are free to edit it however you want afterwards:

```
./bin/vitepressify -i https://geopjr.github.io/gettext.cr/index.json
cd './vitepress-20230313-2578-xyiuim'
pnpm i

# Let's add a LICENSE.md
wget https://raw.githubusercontent.com/GeopJr/gettext.cr/main/LICENSE -O LICENSE.md
mv LICENSE.md docs/

# Build and serve
pnpm run docs:build
pnpm run docs:serve
```

then it should be available under /LICENSE

![image](https://user-images.githubusercontent.com/18014039/224606218-d01e26ed-deaf-4b25-b6f2-272cf5b357ea.png)
